# Generated by Django 4.2.30 on 2026-09-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgrupo', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('poblacion', models.CharField(choices=[('niños_y_adultos', 'Niños y adultos'), ('adultos', 'Adultos'), ('niños', 'Niños'), ('menores_de_dos_anios', 'Menores de dos años')], max_length=30)),
                ('porcion_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unidad_medida', models.TextField(blank=True, null=True)),
                ('kcal', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('proteina_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('grasa_total_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ags_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('agm_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('agp_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('colesterol_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cho_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fibra_g', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('calcio_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fosforo_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('hierro_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('sodio_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('potasio_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('magnesio_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('zinc_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cobre_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('manganeso_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('vit_a_er', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tiamina_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('riboflavina_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('niacina_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('ac_pantotenico_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('piridoxina_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('folato_mcg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('vit_b12_mcg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('vit_c_mg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'alimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupos_alimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlimentoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to='alimentos.alimento')),
            ],
            options={
                'db_table': 'alimentos_guardados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
